package br.com.sulamerica.telesaude.elegibiidade.decisiontable;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Request")
@org.kie.api.definition.type.Description("Objeto de requisição")
public class Request implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Serviço")
	private java.lang.String servico;
	@org.kie.api.definition.type.Label(value = "Produto")
	private int produto;
	@org.kie.api.definition.type.Label(value = "Carteira")
	private java.lang.String carteira;
	@org.kie.api.definition.type.Label(value = "Plano")
	private java.lang.String plano;
	@org.kie.api.definition.type.Label(value = "Empresa")
	private java.lang.String empresa;
	@org.kie.api.definition.type.Label(value = "Cidade")
	private java.lang.String cidade;
	@org.kie.api.definition.type.Label(value = "Cobertura hospitalar")
	private boolean hospitalar;
	@org.kie.api.definition.type.Label(value = "Cobertura ambulatorial")
	private boolean ambulatorial;
	@org.kie.api.definition.type.Label(value = "Adimplente")
	private boolean adimplente;
	@org.kie.api.definition.type.Label(value = "Elegivel")
	private boolean elegivel;
	@org.kie.api.definition.type.Label(value = "Idade")
	private int idade;
	@org.kie.api.definition.type.Label(value = "Atendimentos por ano")
	private int atendimentosAno;

	public Request() {
	}

	public java.lang.String getServico() {
		return this.servico;
	}

	public void setServico(java.lang.String servico) {
		this.servico = servico;
	}

	public int getProduto() {
		return this.produto;
	}

	public void setProduto(int produto) {
		this.produto = produto;
	}

	public java.lang.String getCarteira() {
		return this.carteira;
	}

	public void setCarteira(java.lang.String carteira) {
		this.carteira = carteira;
	}

	public java.lang.String getPlano() {
		return this.plano;
	}

	public void setPlano(java.lang.String plano) {
		this.plano = plano;
	}

	public java.lang.String getEmpresa() {
		return this.empresa;
	}

	public void setEmpresa(java.lang.String empresa) {
		this.empresa = empresa;
	}

	public java.lang.String getCidade() {
		return this.cidade;
	}

	public void setCidade(java.lang.String cidade) {
		this.cidade = cidade;
	}

	public boolean isHospitalar() {
		return this.hospitalar;
	}

	public void setHospitalar(boolean hospitalar) {
		this.hospitalar = hospitalar;
	}

	public boolean isAmbulatorial() {
		return this.ambulatorial;
	}

	public void setAmbulatorial(boolean ambulatorial) {
		this.ambulatorial = ambulatorial;
	}

	public boolean isAdimplente() {
		return this.adimplente;
	}

	public void setAdimplente(boolean adimplente) {
		this.adimplente = adimplente;
	}

	public boolean isElegivel() {
		return this.elegivel;
	}

	public void setElegivel(boolean elegivel) {
		this.elegivel = elegivel;
	}

	public int getIdade() {
		return this.idade;
	}

	public void setIdade(int idade) {
		this.idade = idade;
	}

	public int getAtendimentosAno() {
		return this.atendimentosAno;
	}

	public void setAtendimentosAno(int atendimentosAno) {
		this.atendimentosAno = atendimentosAno;
	}

	public Request(java.lang.String servico, int produto,
			java.lang.String carteira, java.lang.String plano,
			java.lang.String empresa, java.lang.String cidade,
			boolean hospitalar, boolean ambulatorial, boolean adimplente,
			boolean elegivel, int idade, int atendimentosAno) {
		this.servico = servico;
		this.produto = produto;
		this.carteira = carteira;
		this.plano = plano;
		this.empresa = empresa;
		this.cidade = cidade;
		this.hospitalar = hospitalar;
		this.ambulatorial = ambulatorial;
		this.adimplente = adimplente;
		this.elegivel = elegivel;
		this.idade = idade;
		this.atendimentosAno = atendimentosAno;
	}

}