package br.com.sulamerica.telesaude.elegibiidade.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Response implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Elegivel")
	private boolean elegivel;
	@org.kie.api.definition.type.Label("Atendimentos por ano")
	private int atendimentosPorAno;
	@org.kie.api.definition.type.Label("Mensagem")
	private String mensagem;

	@org.kie.api.definition.type.Label("Atendimentos adicionais")
	private int atendimentosAdicionais;

	public Response() {
	}

	public boolean isElegivel() {
		return this.elegivel;
	}

	public void setElegivel(boolean elegivel) {
		this.elegivel = elegivel;
	}

	public int getAtendimentosPorAno() {
		return this.atendimentosPorAno;
	}

	public void setAtendimentosPorAno(int atendimentosPorAno) {
		this.atendimentosPorAno = atendimentosPorAno;
	}

	public java.lang.String getMensagem() {
		return this.mensagem;
	}

	public void setMensagem(java.lang.String mensagem) {
		this.mensagem = mensagem;
	}

	public int getAtendimentosAdicionais() {
		return this.atendimentosAdicionais;
	}

	public void setAtendimentosAdicionais(int atendimentosAdicionais) {
		this.atendimentosAdicionais = atendimentosAdicionais;
	}

	public Response(boolean elegivel, int atendimentosPorAno,
			java.lang.String mensagem, int atendimentosAdicionais) {
		this.elegivel = elegivel;
		this.atendimentosPorAno = atendimentosPorAno;
		this.mensagem = mensagem;
		this.atendimentosAdicionais = atendimentosAdicionais;
	}

}